In [1]:
def add_r(a,b):
    """return type function to find out sum"""
    x = a + b
    return x

In [6]:
def add_nr(a,b):
    """non-return type function"""
    y = a - b
    print(y)

In [7]:
print(3 + add_r(5,3))

11


In [8]:
print(3 + add_nr(5,3))

2


TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [9]:
add_nr(5,3)

2


In [10]:
def returnALot(a,b,c,d):
    """let's return a lot of results"""
    x = a + b
    y = c - d
    return (x,y)

In [11]:
returnALot(3,5,5,3)

(8, 2)

In [12]:
def factorial(n):
    if n == 1:
        return 1
    else:
        return (n*factorial(n-1))

In [13]:
factorial(2)

2

In [15]:
zeros = factorial(1000)

In [18]:
zeroString = str(zeros)

In [20]:
zeroString

'402387260077093773543702433923003985719374864210714632543799910429938512398629020592044208486969404800479988610197196058631666872994808558901323829669944590997424504087073759918823627727188732519779505950995276120874975462497043601418278094646496291056393887437886487337119181045825783647849977012476632889835955735432513185323958463075557409114262417474349347553428646576611667797396668820291207379143853719588249808126867838374559731746136085379534524221586593201928090878297308431392844403281231558611036976801357304216168747609675871348312025478589320767169132448426236131412508780208000261683151027341827977704784635868170164365024153691398281264810213092761244896359928705114964975419909342221566832572080821333186116811553615836546984046708975602900950537616475847728421889679646244945160765353408198901385442487984959953319101723355556602139450399736280750137837615307127761926849034352625200015888535147331611702103968175921510907788019393178114194545257223865541461062892187960223838971476

In [21]:
zeroString.count("0")

472

In [22]:
r = 0.43

In [23]:
import math as math

In [24]:
C = 2*r*math.pi

In [25]:
A = math.pi * (r ** 2)

In [33]:
print("Circumference is:\t",C,"\n and the area is:\t",A)

Circumference is:	 2.701769682087222 
 and the area is:	 0.5808804816487527


In [37]:
from math import radians

In [39]:
dist = r * radians(12)

In [40]:
dist

40317.10572106901

In [38]:
r = 192500

In [41]:
height = [180, 215, 210, 210, 188, 176, 209, 200]
weight = [74, 74, 72, 72, 73, 69, 71, 74]

In [42]:
import numpy as np

In [43]:
np_height = np.array(height)

In [48]:
np_height

array([180, 215, 210, 210, 188, 176, 209, 200])

In [46]:
np_weight = np.array(weight)

In [47]:
np_weight

array([74, 74, 72, 72, 73, 69, 71, 74])

In [49]:
np_height_converted = np_height * 0.453592

In [50]:
np_height_converted

array([81.64656 , 97.52228 , 95.25432 , 95.25432 , 85.275296, 79.832192,
       94.800728, 90.7184  ])

In [51]:
np_weight_converted = np_weight * 0.0254

In [52]:
np_weight_converted

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.7526, 1.8034, 1.8796])

In [53]:
bmi = np_height_converted / np_weight_converted ** 2

In [54]:
bmi

array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 24.80333518,
       25.99036864, 29.14926052, 25.67819599])

In [55]:
light = bmi < 25

In [56]:
light

array([ True, False, False, False,  True, False, False, False])

In [60]:
light[light]

array([ True,  True])

In [64]:
bmi[bmi != 25]

array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 24.80333518,
       25.99036864, 29.14926052, 25.67819599])

In [65]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [66]:
baseball

[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]

In [67]:
np_baseball = np.array(baseball)

In [68]:
np_baseball

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [69]:
np_baseball[2,:]

array([210. ,  98.5])

In [70]:
np_baseball[:,1]

array([ 78.4, 102.7,  98.5,  75.2])

In [71]:
np_baseball[1,0]

215.0

In [73]:
avg = np.mean(np_baseball[:,0])

In [74]:
avg

198.25

In [77]:
np_baseball[0,]

array([180. ,  78.4])